/*
 * This file is generated by jOOQ.
*/
package it.giovannitomasicchio.microservice.jooq;


import it.giovannitomasicchio.microservice.jooq.tables.Author;
import it.giovannitomasicchio.microservice.jooq.tables.Comment;
import it.giovannitomasicchio.microservice.jooq.tables.Post;
import it.giovannitomasicchio.microservice.jooq.tables.PostDetail;
import it.giovannitomasicchio.microservice.jooq.tables.PostTag;
import it.giovannitomasicchio.microservice.jooq.tables.Tag;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PKEY = Indexes0.AUTHOR_PKEY;
    public static final Index COMMENT_PKEY = Indexes0.COMMENT_PKEY;
    public static final Index POST_PKEY = Indexes0.POST_PKEY;
    public static final Index POST_DETAIL_PKEY = Indexes0.POST_DETAIL_PKEY;
    public static final Index POST_TAG_PKEY = Indexes0.POST_TAG_PKEY;
    public static final Index TAG_PKEY = Indexes0.TAG_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index AUTHOR_PKEY = createIndex("author_pkey", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index COMMENT_PKEY = createIndex("comment_pkey", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index POST_PKEY = createIndex("post_pkey", Post.POST, new OrderField[] { Post.POST.ID }, true);
        public static Index POST_DETAIL_PKEY = createIndex("post_detail_pkey", PostDetail.POST_DETAIL, new OrderField[] { PostDetail.POST_DETAIL.ID }, true);
        public static Index POST_TAG_PKEY = createIndex("post_tag_pkey", PostTag.POST_TAG, new OrderField[] { PostTag.POST_TAG.POST_ID, PostTag.POST_TAG.TAG_ID }, true);
        public static Index TAG_PKEY = createIndex("tag_pkey", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
    }
}
