/*
 * This file is generated by jOOQ.
*/
package it.giovannitomasicchio.microservice.jooq;


import it.giovannitomasicchio.microservice.jooq.tables.Author;
import it.giovannitomasicchio.microservice.jooq.tables.Comment;
import it.giovannitomasicchio.microservice.jooq.tables.Post;
import it.giovannitomasicchio.microservice.jooq.tables.PostDetail;
import it.giovannitomasicchio.microservice.jooq.tables.PostTag;
import it.giovannitomasicchio.microservice.jooq.tables.Tag;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -215645277;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.author</code>.
     */
    public final Author AUTHOR = it.giovannitomasicchio.microservice.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = it.giovannitomasicchio.microservice.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>public.post</code>.
     */
    public final Post POST = it.giovannitomasicchio.microservice.jooq.tables.Post.POST;

    /**
     * The table <code>public.post_detail</code>.
     */
    public final PostDetail POST_DETAIL = it.giovannitomasicchio.microservice.jooq.tables.PostDetail.POST_DETAIL;

    /**
     * The table <code>public.post_tag</code>.
     */
    public final PostTag POST_TAG = it.giovannitomasicchio.microservice.jooq.tables.PostTag.POST_TAG;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = it.giovannitomasicchio.microservice.jooq.tables.Tag.TAG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.S_AUTHOR,
            Sequences.S_COMMENT,
            Sequences.S_POST,
            Sequences.S_TAG);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Comment.COMMENT,
            Post.POST,
            PostDetail.POST_DETAIL,
            PostTag.POST_TAG,
            Tag.TAG);
    }
}
