/*
 * This file is generated by jOOQ.
*/
package it.giovannitomasicchio.microservice.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.s_author</code>
     */
    public static final Sequence<Long> S_AUTHOR = new SequenceImpl<Long>("s_author", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.s_comment</code>
     */
    public static final Sequence<Long> S_COMMENT = new SequenceImpl<Long>("s_comment", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.s_post</code>
     */
    public static final Sequence<Long> S_POST = new SequenceImpl<Long>("s_post", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.s_tag</code>
     */
    public static final Sequence<Long> S_TAG = new SequenceImpl<Long>("s_tag", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
