/*
 * This file is generated by jOOQ.
*/
package it.giovannitomasicchio.microservice.jooq;


import it.giovannitomasicchio.microservice.jooq.tables.Author;
import it.giovannitomasicchio.microservice.jooq.tables.Comment;
import it.giovannitomasicchio.microservice.jooq.tables.Post;
import it.giovannitomasicchio.microservice.jooq.tables.PostDetail;
import it.giovannitomasicchio.microservice.jooq.tables.PostTag;
import it.giovannitomasicchio.microservice.jooq.tables.Tag;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = it.giovannitomasicchio.microservice.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT = it.giovannitomasicchio.microservice.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST = it.giovannitomasicchio.microservice.jooq.tables.Post.POST;

    /**
     * The table <code>public.post_detail</code>.
     */
    public static final PostDetail POST_DETAIL = it.giovannitomasicchio.microservice.jooq.tables.PostDetail.POST_DETAIL;

    /**
     * The table <code>public.post_tag</code>.
     */
    public static final PostTag POST_TAG = it.giovannitomasicchio.microservice.jooq.tables.PostTag.POST_TAG;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = it.giovannitomasicchio.microservice.jooq.tables.Tag.TAG;
}
