/*
 * This file is generated by jOOQ.
*/
package it.giovannitomasicchio.microservice.jooq.tables.records;


import it.giovannitomasicchio.microservice.jooq.tables.PostTag;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostTagRecord extends UpdatableRecordImpl<PostTagRecord> implements Record3<BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1665373420;

    /**
     * Setter for <code>public.post_tag.post_id</code>.
     */
    public void setPostId(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.post_tag.post_id</code>.
     */
    public BigDecimal getPostId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.post_tag.tag_id</code>.
     */
    public void setTagId(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.post_tag.tag_id</code>.
     */
    public BigDecimal getTagId() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.post_tag.dummy</code>.
     */
    public void setDummy(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.post_tag.dummy</code>.
     */
    public BigDecimal getDummy() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<BigDecimal, BigDecimal> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return PostTag.POST_TAG.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return PostTag.POST_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return PostTag.POST_TAG.DUMMY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getDummy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getDummy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord value1(BigDecimal value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord value2(BigDecimal value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord value3(BigDecimal value) {
        setDummy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostTagRecord
     */
    public PostTagRecord() {
        super(PostTag.POST_TAG);
    }

    /**
     * Create a detached, initialised PostTagRecord
     */
    public PostTagRecord(BigDecimal postId, BigDecimal tagId, BigDecimal dummy) {
        super(PostTag.POST_TAG);

        set(0, postId);
        set(1, tagId);
        set(2, dummy);
    }
}
